### ISSUE TITLE
Role goals

### ISSUE THREAD

**Issue by mkijowski** [wrightedu/Programmers-Guide-to-the-Galaxy#122]
What do you do every day?  Trying to get an idea of shoes to fill:

* Scrum Master
* Discord Ninja
* Hardware Hacker
* Boffin Buffoon
* Cloning Commander

Looking for a list of duties for each task (IE what a new hire would be expected to know or learn via shadowing)

**Comment by CodingPenguin1** [comment]
# Discord Ninja

- Be able to manually set up channels, roles, permissions, etc
- Be able to use the CSE bot to build the server for a semester (know `-rolemenu`, `-buildserver`, and `-destroyserver` and when to use them)
- Know general structure of code of bot and how to edit/improve

**Comment by mbozada** [comment]
### Scrum Master:
Schedule Sprint Planning, Sprint Review/Retrospective, and Scrum Meetings.
Ensure the team is adhering to the principles of Scrum if not its specific recommendations.

### Resources
[What is Scrum?](https://www.scrum.org/resources/what-is-scrum)
[For Scrum Masters](https://www.scrum.org/pathway/scrum-master)

**Comment by mkijowski** [comment]
For the guide:

A general meeting will consist of:
* check-in
  * is there any old business
  * what have you been working on
  * what are you planning on working on
  * do you need help 
* Scheduling
  * brute force days on board
  * make calendar appts for work
* Planning
  * are we applying scrum
  * brainstorming
  * working sessions
  * who is attending

For all meetings, someone needs to take minutes
* Mike wants to fix industry and the university
* boom
* minutes need to be defined (motions, votes, proposals, todos, etc
* not Matt or project owner/stakeholder
* this needs a bit more work

**Comment by mkijowski** [comment]
Minutes template
* work on this during pgg handbook day?
* reviewed by the team
* best practices
* where does it go

**Comment by mkijowski** [comment]
Did not do
