### ISSUE TITLE
Office / Lab Cleaning

### ISSUE THREAD

**Issue by CodingPenguin1** [wrightedu/Programmers-Guide-to-the-Galaxy#42]
# Russ 303

- [x] Move all post it tagged equipment from 303 rc and hallway outside Gallagher's office to 367 Joshi.
- [x] Stack any books by trash can.

# Oleman 320

- [x] Remove all desktops from 320 Oleman. Good monitors can be kept in back room.
- [x] Keyboards and mice can all be sent to ESPM.
For now let's keep all mini PC towers.

**Comment by mkijowski** [comment]
Move all post it tagged equipment from 303 rc and hallway outside Gallagher's office to 367 Joshi.

There is a Joshi master on the blue key ring.  303 rc should be card swipe accessible.

**Comment by CodingPenguin1** [comment]
> Move all post it tagged equipment from 303 rc and hallway outside Gallagher's office to 367 Joshi.
> 
> There is a Joshi master on the blue key ring. 303 rc should be card swipe accessible.
> 
> Stack any books by trash can.

Timeline for this?

**Comment by CodingPenguin1** [comment]
Lisa might want to help move

**Comment by CodingPenguin1** [comment]
With office move,not lab
