### ISSUE TITLE
Clean out storage room

### ISSUE THREAD

**Issue by CodingPenguin1** [wrightedu/Programmers-Guide-to-the-Galaxy#51]
Wednesday the 29th Starting at 10:00.

- [x] move old equipment to server room
- [x] throw away bad cables
- [x] Keep HP laptops (need linux image), silver micropcs, monitors, and lenovos laptops
- [ ] image some lenovos for loaners?
- [x] discard all vga cables
- [x] discard all dvi cables but ~20
- [x] keep all hdmi and displayport cables
- [x] discard printers
- [x] move excess furniture to storage room (sheth's old office)
- [x] cart all old storage devices over to CaTS for destruction (HDD, disks, etc call x4827 first)
- [x] discard almost all network cables (if any damage at all)

**Comment by mkijowski** [comment]
- [ ] move old equipment to server room
- [ ] throw away bad cables
- [ ] Keep HP laptops (need linux image), silver micropcs, monitors, and lenovos laptops
- [ ] image some lenovos for loaners?

**Comment by mkijowski** [comment]
keep all old laptops, power adapters, and all mini pcs EXCEPT the shiny black mini pc

**Comment by mkijowski** [comment]
keep almost all hardware, especially monitor mounts

**Comment by mkijowski** [comment]
try to clean out the work bench
