### ISSUE TITLE
Review https://github.com/mkijowski/wsu-cs-remote-setup, move over to wrightedu org

### ISSUE THREAD

**Issue by mkijowski** [wrightedu/Programmers-Guide-to-the-Galaxy#53]
come up with better name

check that it is accurate

**Comment by mbozada** [comment]
@mkijowski I'm pretty sure that the guide needs to be updated/expanded(?)

Two things I know for sure need review:
- WSL (Setting it up and how to configure Ubuntu after the fact)
- mingw (We ran into issues installing it when imaging Wischgoll's systems, need to make sure it's still good).

Do you want me to give a go at updating it, or do you want to take care of it?

**Comment by mkijowski** [comment]
closing issue because repo will be deleted
