### ISSUE TITLE
Image Laptops

### ISSUE THREAD

**Issue by mkijowski** [wrightedu/Programmers-Guide-to-the-Galaxy#62]
- [x] check all bios for PXE boot, secure boot off, and  turn off raid
- [x] 2019 old black dell in cse support room get the 346 image
- [x] xtradell-07 refuses to image
- [x] move black Dells to 346
- [x] Touch Screen Bios Settings: Secure Boot Off, Set Admin Password
- [x] dell touch screen devices in Kijowski office get 355 image (on labeled external drive)
- [x] TK laptop (HP) try both images and hope
- [x] debug flaky touch system (bozada note)

**Comment by mbozada** [comment]
One of the touch screen devices wasn't working with the trackpad attached.

Problem:
The touchpad did not work.

Tried Solutions:
Swapped with another keyboard/touchpad accessory, it also didn't work.

Obvious Solution that I forgot to try:
Turning it off and back on again.

Other than that every dell touch screen system was imaged, but the two remaining need run once ran while connected to WSU-Secure (make sure to clear your wifi credentials). @mkijowski said he would finish it up though.

**Comment by mkijowski** [comment]
I finished imaging and clears my credentials.  Still need to debug the one flaky touch system.

**Comment by mbozada** [comment]
The flaky system worked after a reboot.
