### ISSUE TITLE
add info to PGG regarding its use as a dumping station

### ISSUE THREAD

**Issue by mkijowski** [wrightedu/Programmers-Guide-to-the-Galaxy#64]
We are using PGG as a dumping station for issues that are not specifically under a umbrella of a specific project repo. 

Update PGG (the git stuff) notification of "btw this specific repo is being used as a dumping stations not related to other specific objects" and use that as an intro to our workflow (Segway into issues tab etc) 

There are multiple different benefits for doing this.

**Comment by CodingPenguin1** [comment]
Closed by b88519d
