### ISSUE TITLE
Clean up ALL project boards

### ISSUE THREAD

**Issue by mkijowski** [wrightedu/Programmers-Guide-to-the-Galaxy#65]
- [x] flag for removal all stale project boards
- [x] archive/remove stale at sprint review
- [x] setup project board automations for each active project

**Comment by CodingPenguin1** [comment]
Flagging org-level cyberraider for removal

**Comment by CodingPenguin1** [comment]
Flagging [CyberRaider boards](https://github.com/wrightedu/CyberRaider/projects) for removal

**Comment by CodingPenguin1** [comment]
Flagging [competitions-problems board](https://github.com/wrightedu/competition-problems/projects/1) to **NOT** be removed

**Comment by CodingPenguin1** [comment]
Flagging [WSU-CSE-ABET board](https://github.com/wrightedu/WSU-CSE-ABET/projects/1) for removal

**Comment by CodingPenguin1** [comment]
Flagging [autograder/1](https://github.com/wrightedu/autograder/projects/1) for removal

**Comment by CodingPenguin1** [comment]
Flagging [autograder/2](https://github.com/wrightedu/autograder/projects/2) for removal

**Comment by mkijowski** [comment]
all task complete closing
