### ISSUE TITLE
Hiring

### ISSUE THREAD

**Issue by mkijowski** [wrightedu/Programmers-Guide-to-the-Galaxy#79]
- [ ] Send public call for resumes & githubs
  - Send to @mkijowski on Discord

Do you have what it takes to be a @CSE-SUPPORT member?  Do you like programming and working on projects that improve the Computer Science department?  Can you tolerate a corgi herding you around the hallways?  If so apply!

To apply: simply email matthew.kijowski@wright.edu the following:
* your resume in `.pdf` or `.md` format (plus points if its already in github)
* your github username
* The solution to the following problem:

```
In the programming language of your choice, prompt the user for simple 
keyboard input of a string (any number of characters including white-space) 
terminated by a new line.
Then echo or output that provided input to the terminal/standard out.
```

* Include information on how to compile/run your code, and documentation!  Feel free to get creative and brag about it!

**Comment by mbozada** [comment]
Questions:

- What do you think is the coolest thing about computers?
- How do you feel about working in a group?
- Do you consider yourself a leader or a follower?
- What was your favorite class? Why?
- What has your favorite assignment been in any class you've taken so far? Coolest project ever?
- What are you working on outside of class?
- What do you do in your free-time?
- What was your hardest class?
- What topic do you feel the weakest in?
- If we were to work on a similar project, what would you do?
- Why are you interested in this job vs other on-campus positions (CaTS, TAs, etc)?
- What is one trait or skill you have that you think most makes you fit for this position?
